version: '3.9'

services:
  app:
    image: 'node:18.16-alpine'
    container_name: 'elite-events'
    ports:
      - '5173:5173'
    command: npm run dev

    working_dir: /app
    volumes:
      - .:/app
