name: CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Lint Code
      run: npm run lint
      
  unit_test: 
   needs: ['setup']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Run unit tests
     run: npm run test
  
  build: 
   needs: ['setup']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: install dependencies
     run: npm install
   - name: build
     run: npm run build
   
  
  
    
        
