name: CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Lint Code
      run: npm run lint
    - name: Run unit Tests
      run: npm run test
    - name: Run e2e Tests
      uses: cypress-io/github-action@v5.8.2
      with:
        config-file: ./cypress.json
        command: test:cypress
        install: npm install
        install-command: npm install
        runTests: test:cypress
        wait-on-timeout: 4000
        
