name: CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  prepare_setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Lint Code
      run: npm run lint
      
  unit_test:
   needs: prepare_setup
   runs-on: ubuntu-latest
   steps:
    - name: Install Dependencies
      run: npm install
    - name: Run unit Test
      run: npm run test
       
  make_build:
   needs: unit_test
   runs-on: ubuntu-latest
   steps:
    - name: Install Dependencies
      run: npm install
    - name: npm run build
      run: npm run build

