name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:    


jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Lint Code
      run: npm run lint

  unit_test:
   needs: ['setup']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Install Dependencies
     run: npm install
   - name: Run unit tests
     run: npm run test:ci
   - name: Make coverage
     uses: luk-schweizer/jest-code-coverage-badge-action@v1.0.1
     with:
       test-command: npm run test:ci
      # coverage-type: # optional, default is statements
      # Label for the badge
       badge-label: coverage
      # Show jest logo
     #  badge-logo: # optional, default is true
      # Configuration for the badge colors depending on the code coverage percentage
     #  badge-color-configuration: # optional, default is [{"color": "red", ">=": 0, "<": 30 }, {"color": "orange", ">=": 30, "<": 40 },{"color": "yellow", ">=": 40, "<": 60 },{"color": "yellowgreen", ">=": 60, "<": 70 },{"color": "green", ">=": 70, "<": 90 },{"color": "brightgreen", ">=": 90, "<=": 100 }]
      # KVaaS key url where to post coverage values. If not present the action will generate a new url. More info in https://keyvalue.xyz
     #  kvaas-key-url: # optional

  teste2e:
   needs: ['unit_test']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v3
     with:
      node-version: 18
      cache: 'npm'
      cache-dependency-path: ./package-lock.json
   - name: Install dependencies
     run: npm install
   - name: Cypress.io
     uses: cypress-io/github-action@v5.8.2
     with:
      build: npm run build
      start: npm run dev
      browser: chrome



  build:
   needs: ['teste2e']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: install dependencies
     run: npm install
   - name: build
     run: npm run build





