name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:    


jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Lint Code
      run: npm run lint

  unit_test:
   needs: ['setup']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Install Dependencies
     run: npm install
   - name: Run unit tests
     run: npm run test:ci
   - name: make coverage
     uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
     with:
      GITHUB_TOKEN: ${{secrets.USER_GIT}}
     

  teste2e:
   needs: ['unit_test']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v3
     with:
      node-version: 18
      cache: 'npm'
      cache-dependency-path: ./package-lock.json
   - name: Install dependencies
     run: npm install
   - name: Cypress.io
     uses: cypress-io/github-action@v5.8.2
     with:
      build: npm run build
      start: npm run dev
      browser: chrome



  build:
   needs: ['teste2e']
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: install dependencies
     run: npm install
   - name: build
     run: npm run build





